In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
num_rows = np.random.randint(low=10, high=1000)
num_cols = np.random.randint(low=2, high=1000)
X = np.random.normal(size=(num_rows, num_cols))
error = np.random.normal(size=num_rows)

In [3]:
X

array([[-1.578771  ,  1.04921333,  2.35582582, ...,  0.83615558,
        -0.15947612,  0.2106375 ],
       [ 0.83359316, -1.75837843, -0.10642767, ..., -0.18949109,
        -0.51991953,  0.09039556],
       [ 0.98040982,  0.09340535, -0.76350131, ...,  0.59920542,
        -0.71250391, -0.8705424 ],
       ..., 
       [ 1.84881037,  0.55813258, -0.05749412, ..., -1.18858091,
         0.15845484, -0.77447312],
       [ 1.30553059, -0.6804907 , -0.93739091, ...,  0.35070152,
        -0.03091575, -0.52165925],
       [-0.92943859, -1.29847522, -1.18241239, ...,  1.43687597,
        -0.02787083, -0.45998654]])

In [4]:
df = pd.DataFrame(X)

In [5]:
df.head()

0         1         2         3         4         5         6    \
0 -1.578771  1.049213  2.355826  0.525669  0.924195 -1.411512  0.094601   
1  0.833593 -1.758378 -0.106428 -2.072514 -1.875182  1.285696 -0.072586   
2  0.980410  0.093405 -0.763501 -0.122833 -0.698836  0.450425 -1.389063   
3 -1.056293 -0.634185  0.180256 -1.933667 -0.626567  0.999961 -0.017725   
4 -0.877679  0.815477 -1.092786  2.819796 -0.274532 -1.652215 -0.222990   

        7         8         9      ...          381       382       383  \
0 -0.405807 -1.913909 -0.814626    ...     0.606339 -0.892809 -0.339084   
1 -2.974033 -1.063279  0.865398    ...     0.285468 -0.445032  0.153180   
2 -0.343318 -0.388203 -0.132550    ...     1.157676  0.346600 -0.291543   
3  1.076877 -0.348478  0.407883    ...     1.092415 -0.494496  1.734243   
4 -0.094842  0.130413  1.381480    ...    -0.328313  0.313502 -1.330395   

        384       385       386       387       388       389       390  
0  0.419079  0.830226  0.550028 -0.455941  0.836156 -0.159476  0.210637  
1 -0.353425 -0.145823 -0.229449 -1.152294 -0.189491 -0.519920  0.090396  
2  1.234247  0.342310 -1.394649  0.987199  0.599205 -0.712504 -0.870542  
3  1.873984 -0.039871  0.758577 -0.831427  0.841633 -1.548833  0.781434  
4  0.014934 -0.291351  0.832369  0.127525 -1.118597  0.959511 -2.025361  

[5 rows x 391 columns]

In [6]:
error

array([ 1.49423927, -0.7096516 , -2.56492145,  0.83978444,  0.16767612,
        0.01116178, -1.4310155 , -0.83187032, -1.04089967, -0.68360278,
       -0.2738611 , -1.22919567, -0.24513692,  0.32368362, -0.23322992,
        0.85193223,  1.40831327, -0.93966723,  0.62545902,  0.215696  ,
        0.56281155,  1.20421867,  0.30722787, -0.63662259,  0.597039  ,
        0.94523393, -0.22800107, -0.59211622,  1.2440842 , -0.15976557,
        0.29681924,  0.28152215])

In [7]:
Y = np.array([])

In [8]:
for i in range(num_rows):
    col_idx = np.random.randint(low=0, high=num_cols)
    slice_col = X[:, col_idx]
    col_mean = np.mean(slice_col)
    if(X[i, col_idx] < col_mean):
        Y = np.append(Y, )
    
    Y = Y + coef * Y
Y = Y + error  # Add a normal error term

In [9]:
Y.shape

(32,)

In [10]:
    col_idx = np.random.randint(low=0, high=num_cols)
    slice_col = X[:, col_idx]

In [11]:
slice_col

array([ 0.44782712, -1.26012155,  0.55495774,  0.87060779,  0.70320068,
       -0.71606542,  1.50804042,  0.59771206,  0.21977387,  0.34834439,
       -0.48522074,  0.99784988,  0.42184301, -1.49126956,  0.03165407,
        0.28132062, -0.27298773, -0.87504397, -0.21675028, -0.93993049,
       -1.42971798,  1.98646052,  0.56940648,  2.54609004,  0.28197236,
       -0.46271926,  0.71929927,  1.14786742, -0.68937033,  0.84499711,
       -0.24295897, -0.00603878])

In [12]:
np.mean(slice_col)

0.18721968024415928