In [5]:
import numpy as np
import pandas as pd
import torch

From Examples: https://github.com/ast0414/CSE6250BDH-LAB-DL/blob/master/0_Intro_PyTorch.ipynb

In [4]:
np_array = np.array([1., 2., 3.])
print(np_array)
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

# Modify the Tensor
torch_tensor[0] = -1.0
print(np_array)

[1. 2. 3.]

 1
 2
 3
[torch.DoubleTensor of size 3]

[-1.  2.  3.]


Own Example from Pandas

In [6]:
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [1,2,3,4]})

In [12]:
torch_tensor = torch.from_numpy(df.values)

In [13]:
print(torch_tensor)


 1  1
 2  2
 3  3
 4  4
[torch.LongTensor of size 4x2]



## Testing reading dataset

In [16]:
df = pd.read_csv('../data/seizure/seizure_train.csv')

In [19]:
df.y.value_counts()

3    1610
2    1610
5    1610
1    1610
4    1610
Name: y, dtype: int64

In [20]:
df['y'] -= 1

In [21]:
df.y.value_counts()

3    1610
2    1610
1    1610
4    1610
0    1610
Name: y, dtype: int64

In [26]:
df.drop('y', axis=1).values

array([[-104,  -96,  -96, ...,  -77,  -74,  -73],
       [ -58,  -16,   56, ...,    8,   66,  123],
       [-287, -256, -222, ..., -135,  -80,  -39],
       ...,
       [ 177,  153,  151, ...,   12,   44,   52],
       [  62,   88,   93, ...,   37,   27,   44],
       [ -52,  -49,  -39, ..., -131, -124,  -98]])

In [25]:
df.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10 ...  X170  X171  X172  \
0 -104  -96  -96  -99  -82 -100  -98 -107  -97  -87 ...   -83   -77   -88   
1  -58  -16   56  119  134  133   97   74   42   -9 ...  -126  -107   -82   
2 -287 -256 -222 -185 -178 -166 -165 -138 -120  -83 ...  -407  -370  -346   
3    4   14   24   33   10  -27  -40  -14    7   24 ...   -38     2    23   
4  -17  -16  -14    5    6    6   -3    5    2   16 ...    33    26    35   

   X173  X174  X175  X176  X177  X178  y  
0   -76   -86   -69   -77   -74   -73  4  
1   -70   -50   -36     8    66   123  3  
2  -284  -231  -173  -135   -80   -39  0  
3    21   -10   -75  -105   -89   -52  4  
4    24    22    26    21    27    28  1  

[5 rows x 179 columns]

In [27]:
df.y.values

array([4, 3, 0, ..., 2, 1, 4])

In [32]:
df_mlp = df.copy()

In [33]:
df_mlp.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10 ...  X170  X171  X172  \
0 -104  -96  -96  -99  -82 -100  -98 -107  -97  -87 ...   -83   -77   -88   
1  -58  -16   56  119  134  133   97   74   42   -9 ...  -126  -107   -82   
2 -287 -256 -222 -185 -178 -166 -165 -138 -120  -83 ...  -407  -370  -346   
3    4   14   24   33   10  -27  -40  -14    7   24 ...   -38     2    23   
4  -17  -16  -14    5    6    6   -3    5    2   16 ...    33    26    35   

   X173  X174  X175  X176  X177  X178  y  
0   -76   -86   -69   -77   -74   -73  4  
1   -70   -50   -36     8    66   123  3  
2  -284  -231  -173  -135   -80   -39  0  
3    21   -10   -75  -105   -89   -52  4  
4    24    22    26    21    27    28  1  

[5 rows x 179 columns]

In [38]:
df_mlp['X0'] = float(1.0)

In [42]:
df_mlp = df_mlp.astype('float')

In [43]:
df_mlp

X1     X2      X3      X4     X5     X6      X7      X8     X9  \
0    -104.0  -96.0   -96.0   -99.0  -82.0 -100.0   -98.0  -107.0  -97.0   
1     -58.0  -16.0    56.0   119.0  134.0  133.0    97.0    74.0   42.0   
2    -287.0 -256.0  -222.0  -185.0 -178.0 -166.0  -165.0  -138.0 -120.0   
3       4.0   14.0    24.0    33.0   10.0  -27.0   -40.0   -14.0    7.0   
4     -17.0  -16.0   -14.0     5.0    6.0    6.0    -3.0     5.0    2.0   
5    -143.0 -140.0  -132.0  -112.0 -115.0  -99.0  -102.0   -84.0 -104.0   
6     -22.0   -9.0    -4.0    15.0   15.0   18.0    17.0     6.0   -1.0   
7     -20.0  -22.0   -29.0   -34.0  -38.0  -41.0   -46.0   -46.0  -43.0   
8    -264.0 -184.0  -117.0   -48.0   29.0   64.0   114.0   141.0  165.0   
9      83.0   62.0    62.0    42.0  -12.0  -40.0   -53.0   -54.0  -19.0   
10    -75.0  -82.0   -82.0   -86.0  -73.0  -68.0   -73.0   -66.0  -54.0   
11    -61.0  -62.0    -4.0    35.0   54.0   77.0    99.0    63.0    7.0   
12   -173.0 -156.0  -147.0  -111.0  -48.0    6.0    29.0    52.0   24.0   
13     41.0   34.0    26.0    16.0   12.0   22.0    12.0    11.0    8.0   
14    -63.0  -52.0   -83.0  -103.0  -96.0  -86.0   -66.0   -75.0  -95.0   
15   -180.0 -182.0  -177.0  -182.0 -188.0 -167.0  -163.0  -157.0 -168.0   
16     57.0   62.0    42.0    22.0   11.0   19.0    41.0    39.0   57.0   
17     50.0   55.0    51.0    33.0   28.0   33.0    21.0    31.0   27.0   
18    -17.0    3.0    -6.0   -13.0  -33.0  -59.0   -74.0  -104.0 -113.0   
19   -198.0  -14.0   190.0   370.0  470.0  491.0   425.0   339.0  268.0   
20     17.0    5.0    22.0    13.0   36.0   44.0    67.0    78.0   67.0   
21     31.0    8.0    23.0    58.0   47.0   42.0    -6.0   -52.0  -91.0   
22   -394.0 -852.0 -1207.0 -1216.0 -970.0 -656.0  -383.0  -388.0 -546.0   
23    -19.0  -23.0   -10.0    -3.0    2.0   11.0     9.0    34.0   31.0   
24    -27.0    0.0    17.0     2.0  -14.0  -27.0   -55.0   -76.0  -88.0   
25     31.0   34.0    23.0    -9.0  -21.0  -22.0   -32.0   -24.0  -19.0   
26    -33.0  -18.0    10.0    21.0   40.0   35.0    48.0    55.0   43.0   
27    -66.0  -77.0   -88.0  -103.0 -109.0 -100.0  -113.0  -112.0  -97.0   
28     45.0   40.0    48.0    27.0   27.0   33.0    20.0    21.0   33.0   
29     59.0   71.0    94.0   105.0  127.0  120.0    81.0    78.0   59.0   
...     ...    ...     ...     ...    ...    ...     ...     ...    ...   
8020  136.0  159.0   287.0   458.0  598.0  735.0   801.0   833.0  852.0   
8021  101.0  120.0    93.0    82.0   76.0   70.0   116.0   164.0  215.0   
8022   40.0   45.0    39.0    17.0   22.0   27.0    23.0    27.0   19.0   
8023 -255.0 -172.0   -16.0   120.0  151.0   77.0    21.0   -13.0  -64.0   
8024   26.0   20.0    16.0    -2.0   -4.0   -4.0     7.0     2.0   -4.0   
8025  -15.0   -4.0    -4.0    -5.0  -12.0  -22.0   -34.0   -47.0  -54.0   
8026  -77.0  -63.0   -77.0   -63.0  -65.0  -81.0   -74.0   -91.0 -111.0   
8027  -39.0  -40.0   -40.0   -29.0  -31.0  -34.0   -24.0   -13.0   -5.0   
8028  -42.0  -28.0   -40.0   -59.0  -73.0  -82.0   -79.0   -73.0  -64.0   
8029  -15.0  -66.0   -97.0  -118.0 -104.0  -65.0   -56.0   -58.0  -75.0   
8030    9.0    9.0   -10.0   -37.0  -34.0   -1.0    53.0    93.0   97.0   
8031  -11.0   -9.0     0.0    -9.0   13.0   31.0    60.0    52.0   42.0   
8032  -85.0 -100.0  -101.0   -98.0 -107.0 -100.0   -84.0   -86.0  -81.0   
8033  -41.0  -17.0   -46.0   -62.0  -73.0  -81.0   -78.0   -59.0  -83.0   
8034   29.0   28.0    20.0    22.0   -8.0  -18.0   -37.0   -44.0  -69.0   
8035  -78.0 -151.0  -179.0  -164.0 -104.0  -75.0   -68.0   -68.0  -73.0   
8036  -70.0  161.0   257.0   255.0  173.0   14.0  -190.0  -422.0 -549.0   
8037   64.0   56.0    44.0    37.0   42.0   32.0    19.0    11.0   26.0   
8038   10.0    6.0    -6.0     9.0   10.0   15.0    12.0    21.0   16.0   
8039 -151.0 -147.0  -146.0  -139.0 -109.0  -99.0   -74.0   -64.0  -99.0   
8040  -17.0   19.0    10.0    24.0   34.0   31.0    19.0    34.0   22.0   
8041    0.0    1.0    -5.0   -23.0